sudo: true
dist: trusty

language: cpp

addons:
  apt:
    packages:
      - qtbase5-dev

before_script:
  - mkdir build && cd build

script:
  - QT_SELECT=qt4 qmake .. && make -B
  - QT_SELECT=qt5 qmake .. && make -B
